### ISSUE TITLE
TravisCI reports error while installing unf_ext

### ISSUE THREAD

**Issue by zuku** [zuku/bmff#11]
```
Installing uuidtools 2.1.5
Installing unf_ext 0.0.7.2 with native extensions
Installing mime-types 2.99
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /home/travis/.rvm/gems/ruby-head/gems/unf_ext-0.0.7.2/ext/unf_ext
/home/travis/.rvm/rubies/ruby-head/bin/ruby -r ./siteconf20160207-4476-1h43ndi.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/travis/.rvm/rubies/ruby-head/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:541:in `try_link0'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:556:in `try_link'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:765:in `try_func'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:997:in `block in have_library'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:942:in `block in checking_for'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:320:in `open'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:350:in `block in postpone'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:320:in `open'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:346:in `postpone'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:941:in `checking_for'
	from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.4.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'
To see why this extension failed to compile, please check the mkmf.log which can be found here:
  /home/travis/.rvm/gems/ruby-head/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.2/mkmf.log
extconf failed, exit code 1
```

**Comment by zuku** [comment]
> NoMethodError: undefined method `spec' for nil:NilClass

error appeared.
